package apply

import (
	"github.com/spf13/cobra"

	"github.com/giantswarm/microerror"
)

const (
	flagClusterName         = "cluster-name"
	flagClusterManifestFile = "cluster-manifest-file"
)

type flags struct {
	ClusterName         string
	ClusterManifestFile string
}

func (f *flags) Init(cmd *cobra.Command) {
	cmd.Flags().StringVar(&f.ClusterName, flagClusterName, "", `Management cluster name`)
	cmd.Flags().StringVar(&f.ClusterManifestFile, flagClusterManifestFile, "", `Cluster template (generated by kubectl-gs)`)
}

func (f *flags) Validate() error {
	if f.ClusterName == "" {
		return microerror.Maskf(invalidFlagError, "--%s must not be empty", flagClusterName)
	}
	if f.ClusterManifestFile == "" {
		return microerror.Maskf(invalidFlagError, "--%s must not be empty", flagClusterManifestFile)
	}

	return nil
}
